# Generated by Django 5.1.7 on 2025-05-24 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaresponse',
            name='social_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.socialmediasource'),
        ),
        migrations.AddField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='survey',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='core.project'),
        ),
        migrations.AddField(
            model_name='survey',
            name='target_locations',
            field=models.ManyToManyField(related_name='surveys', to='core.location'),
        ),
        migrations.AddField(
            model_name='socialmediaresponse',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_responses', to='core.survey'),
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.survey'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.survey'),
        ),
        migrations.AddField(
            model_name='question',
            name='swot_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.swotcategory'),
        ),
        migrations.AddField(
            model_name='volunteers',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AddField(
            model_name='response',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.volunteers'),
        ),
        migrations.AlterUniqueTogether(
            name='socialmediaresponse',
            unique_together={('survey', 'source_id')},
        ),
    ]
