# Generated by Django 5.1.7 on 2025-04-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteers',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
