# Generated by Django 5.1.7 on 2025-04-21 15:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_volunteers_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteers',
            name='birthdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteers',
            name='sex',
            field=models.CharField(default='M', max_length=2),
            preserve_default=False,
        ),
    ]
