# Generated by Django 5.1.7 on 2025-04-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_volunteers_birthdate_volunteers_sex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='text',
        ),
        migrations.AddField(
            model_name='response',
            name='translated_from',
            field=models.TextField(default=''),
        ),
    ]
