# Generated by Django 5.1.7 on 2025-04-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_response_text_response_translated_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
