# Generated by Django 5.1.7 on 2025-04-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasource',
            name='required_data',
            field=models.CharField(choices=[('all', 'All'), ('sentiment', 'Sentiment'), ('topics', 'Entities and Topics')], default='all', max_length=20),
        ),
    ]
