# Generated by Django 5.1.7 on 2025-04-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_socialmediasource_social_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasource',
            name='social_source',
        ),
    ]
